2017-04-19T01:38:24.455792+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-19T01:38:24.455793+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-04-19T01:38:24.455794+00:00 app[web.1]:     __import__(module)
2017-04-19T01:38:24.455794+00:00 app[web.1]:   File "/app/server.py", line 1, in <module>
2017-04-19T01:38:24.455795+00:00 app[web.1]:     import app as info4300
2017-04-19T01:38:24.455796+00:00 app[web.1]:   File "/app/app/__init__.py", line 3, in <module>
2017-04-19T01:38:24.455797+00:00 app[web.1]:     from app.controllers.concerns import naive_bayes
2017-04-19T01:38:24.455798+00:00 app[web.1]:   File "/app/app/controllers/concerns/naive_bayes.py", line 4, in <module>
2017-04-19T01:38:24.455798+00:00 app[web.1]:     import os, json, nltk
2017-04-19T01:38:24.455803+00:00 app[web.1]: ModuleNotFoundError: No module named 'nltk'
2017-04-19T01:38:24.456285+00:00 app[web.1]: [2017-04-19 01:38:24 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-04-19T01:38:24.458070+00:00 app[web.1]: [2017-04-19 01:38:24 +0000] [8] [ERROR] Exception in worker process
2017-04-19T01:38:24.458071+00:00 app[web.1]: Traceback (most recent call last):
2017-04-19T01:38:24.458072+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-04-19T01:38:24.458073+00:00 app[web.1]:     worker.init_process()
2017-04-19T01:38:24.458074+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-04-19T01:38:24.458074+00:00 app[web.1]:     self.load_wsgi()
2017-04-19T01:38:24.458075+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-04-19T01:38:24.458076+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-19T01:38:24.458076+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-19T01:38:24.458077+00:00 app[web.1]:     self.callable = self.load()
2017-04-19T01:38:24.458078+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-19T01:38:24.458078+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-19T01:38:24.458079+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-19T01:38:24.458079+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-19T01:38:24.458080+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-04-19T01:38:24.458081+00:00 app[web.1]:     __import__(module)
2017-04-19T01:38:24.458081+00:00 app[web.1]:   File "/app/server.py", line 1, in <module>
2017-04-19T01:38:24.458082+00:00 app[web.1]:     import app as info4300
2017-04-19T01:38:24.458083+00:00 app[web.1]:   File "/app/app/__init__.py", line 3, in <module>
2017-04-19T01:38:24.458083+00:00 app[web.1]:     from app.controllers.concerns import naive_bayes
2017-04-19T01:38:24.458084+00:00 app[web.1]:   File "/app/app/controllers/concerns/naive_bayes.py", line 4, in <module>
2017-04-19T01:38:24.458085+00:00 app[web.1]:     import os, json, nltk
2017-04-19T01:38:24.458088+00:00 app[web.1]: ModuleNotFoundError: No module named 'nltk'
2017-04-19T01:38:24.458582+00:00 app[web.1]: [2017-04-19 01:38:24 +0000] [8] [INFO] Worker exiting (pid: 8)
2017-04-19T01:38:24.674045+00:00 app[web.1]: [2017-04-19 01:38:24 +0000] [4] [INFO] Shutting down: Master
2017-04-19T01:38:24.674191+00:00 app[web.1]: [2017-04-19 01:38:24 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-04-19T01:38:24.777950+00:00 heroku[web.1]: State changed from up to crashed
2017-04-19T01:38:24.761247+00:00 heroku[web.1]: Process exited with status 3
2017-04-19T01:38:36.575439+00:00 heroku[web.1]: State changed from crashed to starting
2017-04-19T01:38:46.035096+00:00 heroku[web.1]: Starting process with command `gunicorn server:app`
2017-04-19T01:38:48.612736+00:00 app[web.1]: [2017-04-19 01:38:48 +0000] [4] [INFO] Listening at: http://0.0.0.0:45629 (4)
2017-04-19T01:38:48.612726+00:00 app[web.1]: [2017-04-19 01:38:48 +0000] [4] [INFO] Starting gunicorn 19.7.1
2017-04-19T01:38:48.612736+00:00 app[web.1]: [2017-04-19 01:38:48 +0000] [4] [INFO] Using worker: sync
2017-04-19T01:38:48.616303+00:00 app[web.1]: [2017-04-19 01:38:48 +0000] [8] [INFO] Booting worker with pid: 8
2017-04-19T01:38:48.634030+00:00 app[web.1]: [2017-04-19 01:38:48 +0000] [9] [INFO] Booting worker with pid: 9
2017-04-19T01:38:49.668361+00:00 heroku[web.1]: State changed from starting to up
2017-04-19T01:38:51.544831+00:00 app[web.1]: [2017-04-19 01:38:51 +0000] [8] [ERROR] Exception in worker process
2017-04-19T01:38:51.544862+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-04-19T01:38:51.544855+00:00 app[web.1]: Traceback (most recent call last):
2017-04-19T01:38:51.544863+00:00 app[web.1]:     worker.init_process()
2017-04-19T01:38:51.544864+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-04-19T01:38:51.544864+00:00 app[web.1]:     self.load_wsgi()
2017-04-19T01:38:51.544865+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-04-19T01:38:51.544866+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-19T01:38:51.544867+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-19T01:38:51.544868+00:00 app[web.1]:     self.callable = self.load()
2017-04-19T01:38:51.544868+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-19T01:38:51.544869+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-19T01:38:51.544870+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-19T01:38:51.544870+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-19T01:38:51.544871+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-04-19T01:38:51.544871+00:00 app[web.1]:     __import__(module)
2017-04-19T01:38:51.544872+00:00 app[web.1]:   File "/app/server.py", line 1, in <module>
2017-04-19T01:38:51.544872+00:00 app[web.1]:     import app as info4300
2017-04-19T01:38:51.544873+00:00 app[web.1]:   File "/app/app/__init__.py", line 3, in <module>
2017-04-19T01:38:51.544874+00:00 app[web.1]:     from app.controllers.concerns import naive_bayes
2017-04-19T01:38:51.544874+00:00 app[web.1]:   File "/app/app/controllers/concerns/naive_bayes.py", line 4, in <module>
2017-04-19T01:38:51.544874+00:00 app[web.1]:     import os, json, nltk
2017-04-19T01:38:51.544879+00:00 app[web.1]: ModuleNotFoundError: No module named 'nltk'
2017-04-19T01:38:51.545397+00:00 app[web.1]: [2017-04-19 01:38:51 +0000] [8] [INFO] Worker exiting (pid: 8)
2017-04-19T01:38:51.547030+00:00 app[web.1]: [2017-04-19 01:38:51 +0000] [9] [ERROR] Exception in worker process
2017-04-19T01:38:51.547031+00:00 app[web.1]: Traceback (most recent call last):
2017-04-19T01:38:51.547032+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-04-19T01:38:51.547033+00:00 app[web.1]:     worker.init_process()
2017-04-19T01:38:51.547033+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-04-19T01:38:51.547034+00:00 app[web.1]:     self.load_wsgi()
2017-04-19T01:38:51.547035+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-04-19T01:38:51.547035+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-04-19T01:38:51.547036+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-04-19T01:38:51.547037+00:00 app[web.1]:     self.callable = self.load()
2017-04-19T01:38:51.547038+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-04-19T01:38:51.547038+00:00 app[web.1]:     return self.load_wsgiapp()
2017-04-19T01:38:51.547039+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-04-19T01:38:51.547040+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-04-19T01:38:51.547040+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-04-19T01:38:51.547041+00:00 app[web.1]:     __import__(module)
2017-04-19T01:38:51.547041+00:00 app[web.1]:   File "/app/server.py", line 1, in <module>
2017-04-19T01:38:51.547042+00:00 app[web.1]:     import app as info4300
2017-04-19T01:38:51.547043+00:00 app[web.1]:   File "/app/app/__init__.py", line 3, in <module>
2017-04-19T01:38:51.547043+00:00 app[web.1]:     from app.controllers.concerns import naive_bayes
2017-04-19T01:38:51.547044+00:00 app[web.1]:   File "/app/app/controllers/concerns/naive_bayes.py", line 4, in <module>
2017-04-19T01:38:51.547044+00:00 app[web.1]:     import os, json, nltk
2017-04-19T01:38:51.547047+00:00 app[web.1]: ModuleNotFoundError: No module named 'nltk'
2017-04-19T01:38:51.551659+00:00 app[web.1]: [2017-04-19 01:38:51 +0000] [9] [INFO] Worker exiting (pid: 9)
2017-04-19T01:38:51.757152+00:00 app[web.1]: [2017-04-19 01:38:51 +0000] [4] [INFO] Shutting down: Master
2017-04-19T01:38:51.757336+00:00 app[web.1]: [2017-04-19 01:38:51 +0000] [4] [INFO] Reason: Worker failed to boot.
2017-04-19T01:38:51.954945+00:00 heroku[web.1]: State changed from up to crashed
2017-04-19T01:38:51.933208+00:00 heroku[web.1]: Process exited with status 3
2017-04-19T01:38:52.849476+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=airbnbpricesuggestion.herokuapp.com request_id=8d419265-2240-4560-8c14-a49a79f786f8 fwd="74.79.254.219" dyno=web.1 connect=1ms service= status=503 bytes= protocol=https
2017-04-19T01:39:06.342498+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=airbnbpricesuggestion.herokuapp.com request_id=15b576ed-fb2b-4c55-a153-d093351dd5d2 fwd="74.79.254.219" dyno= connect= service= status=503 bytes= protocol=https
